# Generated by Django 5.2.6 on 2025-11-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Client IP address (IPv4 or IPv6)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the request was made')),
                ('path', models.CharField(db_index=True, help_text='URL path requested (e.g., /admin, /login)', max_length=255)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', '-timestamp'], name='ip_tracking_ip_addr_f0dbdd_idx'), models.Index(fields=['path', '-timestamp'], name='ip_tracking_path_febde3_idx')],
            },
        ),
    ]
