# Generated by Django 5.2.8 on 2025-11-09 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='IP address to block (IPv4 or IPv6)', unique=True)),
                ('reason', models.TextField(blank=True, help_text="Reason for blocking this IP (e.g., 'Brute force attack')")),
                ('blocked_at', models.DateTimeField(auto_now_add=True, help_text='When this IP was blocked')),
                ('blocked_by', models.CharField(blank=True, help_text='Admin username who blocked this IP', max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this block expires (null = permanent)', null=True)),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=255)),
                ('blocked_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ip_tracking.blockedip')),
            ],
            options={
                'verbose_name': 'Blocked Attempt',
                'verbose_name_plural': 'Blocked Attempts',
                'ordering': ['-timestamp'],
            },
        ),
    ]
